services:
  - docker

language: node_js
node_js:
  - "8"

jobs:
  include:
  - stage: Build Docker Container
    script:
      - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
      - docker run -d $DOCKER_IMAGE:$TRAVIS_COMMIT
      - docker ps | grep -q vc-documentation
    deploy:
      provider: script
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_USERNAME/$DOCKER_IMAGE:$TRAVIS_COMMIT
        - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$TRAVIS_COMMIT
      on:
          branch: master
  - stage: Deploy Production
    before_deploy:
        - curl -k -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
        - chmod +x sloppy
    deploy:
        provider: script
        script:
            - ./sloppy change -v docker_image:"$DOCKER_IMAGE:$TRAVIS_COMMIT" -v domain:"$DOMAIN" ./sloppy.json
        on:
            branch: master
