services:
  - docker

language: node_js
node_js:
  - "8"

jobs:
  include:
  - stage: Build Docker Container
    script:
      - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
      - docker run -d $DOCKER_IMAGE:$TRAVIS_COMMIT
      - docker ps | grep -q vc-documentation
    deploy:
      provider: script
      script: bash scripts/docker-hub-deploy.sh
      on:
          branch: master
  - stage: Deploy Production
    before_deploy:
        - curl -k -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
        - chmod +x sloppy
    deploy:
        provider: script
        script: bash scripts/production-deploy.sh
        on:
            branch: master
